export const ADD_SESSION = 'ADD_SESSION'

export const CLEAR_SESSION = 'CLEAR_SESSION'

export const SET_CONFIG = 'SET_CONFIG'

export const TOGGLE_ENABLE_RULE = 'TOGGLE_ENABLE_RULE'

export const TOGGLE_ENABLE_HTTPS = 'TOGGLE_ENABLE_HTTPS'

export const ADD_RULE = 'ADD_RULE'

export const UPDATE_RULE = 'UPDATE_RULE'

export const DELETE_RULE = 'DELETE_RULE'
